test-hdc-bionic:
  image: repo.tok.ipp.cas.cz:5050/compass-tokamak/hdc/test-hdc-bionic
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    - cd python
    - python3 -m pip install .
    - pytest
    - cd tests_binder
    - ./run

test-hdc-xenial:
  image: repo.tok.ipp.cas.cz:5050/compass-tokamak/hdc/test-hdc-xenial
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    - cd python
    - python3 -m pip install .
    - pytest
    - cd tests_binder
    - ./run

test-hdc-centos-7:
  image: repo.tok.ipp.cas.cz:5050/compass-tokamak/hdc/test-hdc-centos-7
  script:
    - mkdir build
    - cd build
    - cmake3 .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    - cd python
    - python3 -m pip install .
    - pytest
    - cd tests_binder
    - FC=gfortran ./run

test-hdc-fedora-31:
  image: repo.tok.ipp.cas.cz:5050/compass-tokamak/hdc/test-hdc-fedora-31
  script:
    - mkdir build
    - cd build
    - cmake3 .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    # Sorry, I will not re-rerun tests because of broken python in docker.
    #- cd python
    #- python3 -m pip install .
    #- pytest
    #- cd tests_binder
    #- FC=gfortran ./run
