test-bionic:
  #variables:
    #CI_DEBUG_TRACE: "true"
  image: dockerhub.tok.ipp.cas.cz:5000/ubuntu-bionic-hdc-prereq
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    - cd python
    - python3 setup.py build
    - python3 setup.py test
    - python3 setup.py install
    - apt install -y python3-jinja2
    - cd ../../utils/binder/tests/
    - python3 -m pip install ..
    - export LC_ALL=C.UTF-8 LANG=C.UTF-8
    - ./run

test-xenial:
  image: dockerhub.tok.ipp.cas.cz:5000/ubuntu-xenial-hdc-prereq
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../install
    - make -j
    - make test
    - make install
    - cd python
    - python3 setup.py build
    - python3 setup.py test
    - python3 setup.py install
    - apt install -y python3-jinja2 pkg-config python3-pytest
    - cd ../../utils/binder/tests/
    - python3 -m pip install ..
    - export LC_ALL=C.UTF-8 LANG=C.UTF-8
    - ./run

test-centos7:
  image: dockerhub.tok.ipp.cas.cz:5000/centos-7-hdc-prereq
  script:
    - export PATH=/opt/rh/devtoolset-7/root/usr/bin:$PATH
    - mkdir build
    - cd build
    - cmake3 -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
    - make -j
    - make test
    - make install
    - cd python
    - python3.6 setup.py build
    # Temporarly turned off
    #- python3.6 setup.py test

test-fedora-28:
  image: dockerhub.tok.ipp.cas.cz:5000/fedora-28-hdc-prereq
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
    - make -j
    - make test
    - make install
    - cd python
    - python3 setup.py build
    # Temporarly turned off
    #- python3 setup.py test
