# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: matrim/cmake-examples:3.5.1

pipelines:
  default:
    - step:
        script:
          - apt-get update -y
          - apt-get upgrade -y
          - apt-get install -y libboost-all-dev gfortran libhdf5-dev cython
          - mkdir build
          - cd build
          - cmake ..
          - make
          - make test
